### ISSUE TITLE
Link para WPeCommerce no README está errado.

### ISSUE THREAD

**Issue by macarena** [pagseguro/wpecommerce#3]
O link não joga para o site do WPeCommerce.

**Comment by s2it-moscou** [comment]
@macarena Obrigado pela contribuição, será passado á equipe de Desenvolvimento do Pagseguro para correção do Link para WPeCommerce no README.

**Comment by s2it-moscou** [comment]
@macarena  Obrigado pela contribuição, foi corrigido o Link para WPeCommerce no README.
